meetsmore/nittei

- .github/workflows/release.yml
- scheduler/clients/javascript/.npmrc
- scheduler/clients/javascript/package.json
- [ci] Publish client lib on tags
> [TS-1038] ci/adapt publish client lib

- scheduler/Cargo.lock
- scheduler/Cargo.toml
- scheduler/crates/api/Cargo.toml
- scheduler/src/main.rs
- scheduler/src/telemetry.rs
- Adapted logs & tracing configuration for our use case
- Integration is not yet perfect for DD, but it gives a good start
- Will likely need to adapt for linking traces with logs
- Will likely need to adapt for adding some metadata fields to logs
> [TS-1193] feat: start implementing tracing for dd

- scheduler/clients/javascript/lib/userClient.ts
Fix https://github.com/meetsmore/nittei/pull/26#discussion_r1721398200
> [NO-ISSUE] fix: use uuid as key

- scheduler/debian.Dockerfile
- scripts/run_tests.sh
- Update Rust version in Docker to match local dev
- Improve test logic so that it waits for PG to be ready more deterministically
> [NO-ISSUE] chore: small improvements

- charts/nittei/Chart.yaml
- charts/nittei/templates/service.yaml
- charts/nittei/values.yaml
- Helm chart: allow to specify service's annotations
- Helm chart: increase version
- Helm chart: add correct default paths and ports for probes
> [NO-ISSUE] fix(helm): add annotations

- charts/nittei/Chart.yaml
- charts/nittei/templates/service.yaml
- Fix again Helm chart's annotations
- Update chart's version
> fix(chart): annotations

- charts/nittei/Chart.yaml
- charts/nittei/templates/service.yaml
- charts/nittei/values.yaml
- [chart] Allow to specify service's targetPort
- [chart] Increase version
> fix(chart): allow to specify service's targetPort

- charts/nittei/templates/deployment.yaml
[chart] Fix position of `revisionHistoryLimit`
> fix(chart): revision history limit position

- Cargo.lock
- bins/nittei/Cargo.toml
- bins/nittei/tests/api_loadtests.rs
- bins/nittei/tests/collective_team_scheduling.rs
- bins/nittei/tests/group_team_scheduling.rs
- bins/nittei/tests/helpers/setup.rs
- bins/nittei/tests/round_robin_scheduling.rs
- clients/javascript/lib/baseClient.ts
- clients/javascript/lib/calendarClient.ts
- clients/javascript/lib/helpers/datesConverters.ts
- clients/javascript/lib/index.ts
- clients/javascript/tests/requirements/loadTests.spec.ts
- justfile
- Add a few basic load tests
- It's better than nothing, but it isn't super conclusive
- We will need to test more outside localhost
In local
```
[single] Time to create 300 events: 1.029547833s
[single] Time to fetch 300 events: 17.579709ms
test loadtests_single_user ... ok
[multiple] Time to create 3000 events: 8.425896792s
[multiple] Time to fetch 300 events: 15.724125ms
[multiple] Time to freebusy 300 events: 7.152125ms
[multiple] Time to freebusy 3000 events: 75.487375ms
test loadtests_multi_users ... ok
[single_big] Time to create 10800 events: 25.774756291s
[single_big] Time to fetch 900 events: 38.515833ms
test loadtests_single_user_lots_of_data ... ok
```
> test: add basic load tests

- clients/javascript/package.json
- pnpm-lock.yaml
Includes
- https://github.com/meetsmore/nittei/pull/66
- https://github.com/meetsmore/nittei/pull/67
- https://github.com/meetsmore/nittei/pull/71
> [dependabot] update js deps

- crates/infra/src/repos/mod.rs
- Make it so that the app doesn't crash if it detects applied migrations it doesn't know
> fix: avoid app failing on unknown migrations

- .github/workflows/js-client-test.yml
- [ci] Make sure Rust is installed the same way in all workflows
> ci: setup rust

- Cargo.lock
- clients/javascript/lib/gen_types/serde_json/JsonValue.ts
- clients/javascript/tests/calendarEvent.spec.ts
- crates/api_structs/Cargo.toml
- crates/domain/Cargo.toml
- [ts-rs dependency] Temporarily use Git repository + Git tag in order to get the improvements regarding the JSON value type
> feat: update ts-rs and target git ref for metadata's improvements

- charts/nittei/templates/deployment.yaml
- charts/nittei/values.yaml
- Adapt also Helm chart so that it has
- Correct environment variables
- Correct Docker registry (https://hub.docker.com/r/meetsmore/nittei)
> feat: update helm chart

- charts/nittei/templates/deployment.yaml
- charts/nittei/values.yaml
- [chart] Fix usage of env var for HOST
- [chart] Fix indentation when defining `env`
> fix: chart

- crates/api/src/lib.rs
- Just add a few logs on startup to understand better what is happening
> chore: add more logs at startup

- clients/javascript/package.json
- package.json
- pnpm-lock.yaml
- Updated a few Nodejs dependencies
> chore: update JS dependencies

- clients/javascript/lib/index.ts
- Expose Axios Client to JS lib's users
- Allow to add custom interceptors/middlewares (e.g. for tracing)
> feat: js lib expose axios client

- charts/nittei/templates/deployment.yaml
- Fix order when merging environment variables in Helm chart
> fix(helm): merge of env vars

- clients/javascript/lib/accountClient.ts
- clients/javascript/tests/account.spec.ts
- Add function for querying the new search events API at the account level (follow-up of https://github.com/meetsmore/nittei/pull/183)
> fix(js client): add search events in account function

- crates/api/src/event/subscribers/mod.rs
- crates/api/src/job_schedulers.rs
- Remove a log that is a little spammy
- Change a log to `debug` as it's not useful for us, at least for now (reminders)
> chore: adapt logs

- alpineWithDD.Dockerfile
- debianWithDD.Dockerfile
- Add one more type of profiling when using DD profiler (https://github.com/DataDog/ddprof?tab=readme-ov-file#memory-leaks)
> feat(profiling): enable live heap with DD

- charts/nittei/values.yaml
- Add slight delay to probes to avoid receiving calls too early
> fix(probes): add a small delay

- clients/javascript/lib/gen_types/CalendarEventSort.ts
- crates/domain/src/event.rs
- crates/infra/src/repos/event/calendar_event/postgres.rs
- Add possibility to sort on `created` field when searching for events
> feat(search events): add createdAt sort

- crates/infra/migrations/20250226000000_add_indexes_for_search.sql
- Add some more indexes on CalendarEvents in order to handle search queries efficiently
- More will likely follow-up
- I'll review all the queries we do on our side to be sure too
> feat: add some search indexes

- Cargo.lock
- crates/infra/Cargo.toml
- Update sqlx (Postgres lib) from 0.8.2 to 0.8.3
> feat: update sqlx

- Cargo.lock
- bins/nittei/Cargo.toml
> feat: update jemalloc

- clients/javascript/lib/gen_types/AccountSearchEventsRequestBodyFilter.ts
- clients/javascript/lib/gen_types/SearchEventsRequestBodyFilter.ts
- clients/javascript/tests/account.spec.ts
- crates/api/src/account/account_search_events.rs
- crates/api/src/event/search_events.rs
- crates/api_structs/src/account/api.rs
- crates/api_structs/src/event/api.rs
- crates/infra/src/repos/event/calendar_event/mod.rs
- crates/infra/src/repos/event/calendar_event/postgres.rs
- Allow to select only events that have recurrence when searching for events
> feat(search events): allow to search events with recurrence

- clients/javascript/lib/gen_types/AccountSearchEventsRequestBodyFilter.ts
- clients/javascript/lib/gen_types/SearchEventsRequestBodyFilter.ts
- clients/javascript/tests/account.spec.ts
- crates/api/src/account/account_search_events.rs
- crates/api/src/event/search_events.rs
- crates/api_structs/src/account/api.rs
- crates/api_structs/src/event/api.rs
- crates/infra/src/repos/event/calendar_event/mod.rs
- crates/infra/src/repos/event/calendar_event/postgres.rs
- Allow to search on `originalStartTime`
> feat: allow to query on originalStartTime

- clients/javascript/lib/gen_types/AccountSearchEventsRequestBodyFilter.ts
- clients/javascript/lib/gen_types/SearchEventsRequestBodyFilter.ts
- crates/api/src/account/account_search_events.rs
- crates/api/src/event/search_events.rs
- crates/api_structs/src/account/api.rs
- crates/api_structs/src/event/api.rs
- crates/infra/src/repos/event/calendar_event/mod.rs
- crates/infra/src/repos/event/calendar_event/postgres.rs
- Allow to query on `recurringEventUid`
> feat: allow to query on recurringEventUid

- .github/workflows/js-client-test.yml
- [ci] Improve waiting strategy for server
- [ci] Print logs of server at the end of JS tests
> ci: improve debug and wait

- .github/workflows/js-client-test.yml
- .github/workflows/server-test.yml
- alpine.Dockerfile
- alpineWithDD.Dockerfile
- debian.Dockerfile
- debianWithDD.Dockerfile
> feat: update to Rust 1.85.1

- crates/api/src/account/account_search_events.rs
- crates/api/src/event/search_events.rs
- crates/utils/src/config.rs
- Increased default nb of events and max limit nb of events linked when searching
> fix: increase limits

- crates/api/src/shared/auth/route_guards.rs
- crates/infra/src/repos/account/postgres.rs
- crates/infra/src/repos/calendar/postgres.rs
- crates/infra/src/repos/event/calendar_event/postgres.rs
- crates/infra/src/repos/user/postgres.rs
- Improve tracing on important functions
- Add tracing on auth middlewares
- Add missing tracing on some infra functions
- Improve tracing in calendar_event's infra functions by logging the parameters too
> feat: improve tracing

- crates/api/src/calendar/get_calendar_events.rs
- crates/api/src/event/get_event_instances.rs
- crates/api/src/event/get_events_by_calendars.rs
- crates/api/src/event/get_events_for_users_in_time_range.rs
- crates/api/src/service/get_service_bookingslots.rs
- crates/api/src/user/get_multiple_users_freebusy.rs
- crates/api/src/user/get_user_freebusy.rs
- crates/infra/src/config.rs
- crates/utils/src/config.rs
- Moved configuration of max timespan duration to env vars + increased values
> refactor: move max timespan duration to global config (env vars)

- Cargo.lock
- bins/nittei/Cargo.toml
- bins/nittei/src/telemetry.rs
- crates/api/Cargo.toml
- Update tracing/telemetry dependencies
> [NO-ISSUE] feat: update tracing libs

- .github/workflows/_build-and-merge-docker.yml
- alpine.Dockerfile
- alpineWithDD.Dockerfile
- crates/api/src/account/account_search_events.rs
- crates/api/src/account/create_account.rs
- crates/api/src/calendar/create_calendar.rs
- crates/api/src/calendar/get_calendar.rs
- crates/api/src/calendar/get_calendars.rs
- crates/api/src/event/create_batch_events.rs
- crates/api/src/event/create_event.rs
- crates/api/src/event/delete_event.rs
- crates/api/src/event/delete_many_events.rs
- crates/api/src/event/get_event.rs
- crates/api/src/event/get_event_by_external_id.rs
- crates/api/src/event/get_events_for_users_in_time_range.rs
- crates/api/src/event/search_events.rs
- crates/api/src/event/update_event.rs
- crates/api/src/status/mod.rs
- crates/api/src/user/create_user.rs
- crates/api/src/user/delete_user.rs
- crates/api/src/user/update_user.rs
- debian.Dockerfile
- debianWithDD.Dockerfile
- Add error logs for main operations instead of silently ignoring the error
- Add commit hash and repo URL in Docker images
> feat: add more errors logs + dd integration

- charts/nittei/templates/podDisruptionBudget.yaml
- charts/nittei/values.yaml
- [helm chart] Add configuration for k8s PodDisruptionBudget
> feat(helm): add pod disruption budget configuration

- .github/workflows/js-client-test.yml
- [ci] Try to improve the stability of the JS tests
> ci: reduce flakiness

- crates/api/src/lib.rs
- crates/infra/src/config.rs
- crates/infra/src/repos/mod.rs
- Improve startup logs
- Will merge master with https://github.com/meetsmore/nittei/pull/338 into this once that one is merged
> chore: improve startup logs

- crates/infra/.sqlx/query-19641b42442bf7e364c0ed465033d6e22bec7b15f2ca4c826dda8deaf5a4ae61.json
- crates/infra/.sqlx/query-3630fca38f7591d10e955848a891d31803fd0e727d72fb25ea4fa6293315d74e.json
- crates/infra/.sqlx/query-5102628702efe5c825127f51473de67b9b66eb66ec82d7a79b4c6f1ce1a5664c.json
- crates/infra/src/repos/event/calendar_event/postgres.rs
- Make the query for "events during timespan" inclusive
> fix: make timespan inclusive

- alpine.Dockerfile
- alpineWithDD.Dockerfile
- debian.Dockerfile
- debianWithDD.Dockerfile
> feat: update Rust to 1.88

- clients/javascript/lib/baseClient.ts
- clients/javascript/lib/index.ts
- Improve configuration of keep-alive in JS client
- Avoid having opened infinite sockets
> feat(client): improve keep-alive

- clients/javascript/lib/baseClient.ts
- Improve error handling in the JS client - avoid throwing HTTP errors directly when there's no status code
> refactor(js client): improve error handling for http client

- charts/nittei/templates/deployment.yaml
- charts/nittei/values.yaml
- Add possibility to configure `topologySpreadConstraints`
> feat(chart): add topology spread constraint config

- Cargo.lock
- crates/api/Cargo.toml
- Update Rust dependencies (ran `cargo update` + updated manually 1 crate)
> feat: update Rust dependencies

- biome.json
- clients/javascript/lib/baseClient.ts
- clients/javascript/lib/helpers/credentials.ts
- clients/javascript/package.json
- package.json
- pnpm-lock.yaml
- Update JS dependencies
- Fix typing issues with headers
- Fix Biome configuration
> feat(js): update dependencies

- Cargo.lock
> feat: update dependencies

- charts/nittei/templates/deployment.yaml
- Fix Helm chart and use `targetPort` in pod's ports configuration, as that's what is actually used
> fix(chart): use targetPort

- .github/workflows/js-client-test.yml
- .github/workflows/server-test.yml
- alpine.Dockerfile
- alpineWithDD.Dockerfile
- debian.Dockerfile
- debianWithDD.Dockerfile
> feat: update Rust to 1.89

- clients/javascript/tests/calendarEvent.spec.ts
- Add a simple additional test to check that exception are correctly fetched for timespan endpoint
> test(timespan): add test on exception

- clients/javascript/tests/calendarEvent.spec.ts
- crates/api/src/event/update_event.rs
- Fix `recurring_until` not reset when `recurrence` is reset
> fix(recurring until): not reset

- crates/infra/migrations/20250916183100_add_additional_index_cross_users.sql
- Add additional index for cross-users queries (in same account)
> feat: add index for cross-users queries

- .github/workflows/js-client-test.yml
- .github/workflows/server-test.yml
- alpine.Dockerfile
- alpineWithDD.Dockerfile
- debian.Dockerfile
- debianWithDD.Dockerfile
> feat: update Rust to 1.90.0
