scheduler/crates/api/src/lib.rs
- Hide the background job behind an environment variable
- I'm thinking of extracting all env vars into one single file (like we do with `config` in Node) so that it's easy to see what are all env vars. Right now they are split into multiple files inside the code
- Ongoing in  https://github.com/meetsmore/nittei/pull/6
=> [NO-ISSUE] refactor: hide reminder job behind an env var/flag

charts/nittei/Chart.yaml, charts/nittei/templates/deployment.yaml, charts/nittei/values.yaml
- Allow all "envs" config in the Helm chart
- Upgrade Helm chart so that we can make a new release
=> [NO-ISSUE] fix(helm): allow all "envs" values + update chart version

charts/nittei/Chart.yaml, charts/nittei/templates/deployment.yaml
- Remove check on DATABASE_URL
- We allow all envs now (https://github.com/meetsmore/nittei/pull/34)
- TODO (later): add explaantion of expected env vars in chart's folder and in values.yml
- Update chart version for triggering new deployment
=> [NO-ISSUE] fix: remove database_url check in chart

scheduler/crates/infra/src/repos/mod.rs
- By default, execute the DB migrations at startup
- Add env var to skip if needed
=> [NO-ISSUE] feat: run migrations at startup

scheduler/crates/api/src/lib.rs, scheduler/crates/infra/src/config.rs
- Allow to specify host address to be bound via env var (127.0.0.1 is default, but we want 0.0.0.0 when deployed)
- `NITTEI_HOST`
- Rename env var `PORT` to `NITTEI_PORT`
=> [NO-ISSUE] fix: allow to bind other host with env var

scheduler/clients/javascript/lib/healthClient.ts, scheduler/clients/rust/src/status.rs, scheduler/crates/api/src/http_logger.rs, scheduler/crates/api/src/lib.rs, scheduler/crates/api/src/status/mod.rs, scheduler/src/telemetry.rs
- Change URL for healthcheck
- Make HTTP logger ignore healthcheck route
- Log internal error of tracing as warning (e.g. DD agent rejecting traces)
=> [NO-ISSUE] fix/adapt logging tracing healthcheck

charts/nittei/Chart.yaml, charts/nittei/templates/deployment.yaml, charts/nittei/values.yaml
- [chart] Add `revisionHistoryLimit` variable
- Default to 5 (I believe it's 10 the "true" default value ?)
=> chore: add revisionHistoryLimit to chart

.github/workflows/server-test.yml, scheduler/.config/nextest.toml
- Remove Nextest config
- Use `cargo test` directly in CI
- Add `RUST_BACKTRACE` env var to force backtraces to be created
=> chore: remove nextest config

.github/workflows/js-client-test.yml, scheduler/clients/javascript/tests/helpers/fixtures.ts, scheduler/crates/infra/src/config.rs
- Make the secret for creating account a hardcoded value in dev
- This allows to run in 2 terminals `just dev` (launch backend) and `pnpm run test` (launch client lib's tests), and make it work out-of-the-box
- In prod, it still generates a random secret
=> fix(local dev): make app use hardcoded create account secret

clients/javascript/tests/requirements/loadTests.spec.ts
- Avoid testing the duration in the JS tests too as the CI is unreliable
=> test: do not test duration

.github/dependabot.yml, Cargo.toml
- For dependabot, specify only the monorepo root, both for pnpm and cargo
=> fix: dependabot paths

.github/workflows/release.yml
- Just added some logs in the CI for debugging the Helm release, as it seems all releases are marked as `latest` (even prereleases)
=> ci: debug mark as latest

package.json, pnpm-lock.yaml
- Just add `biome` as monorepo "main dev dependencies" so that it's picked up by the VSCode extension
=> fix: add biome as monorepo dependency

charts/nittei/templates/deployment.yaml
- Fix an issue with Helm chart - `valueFrom` for environment variables weren't taken into account
=> fix: Helm chart valueFrom not taken into account

clients/javascript/package.json, clients/javascript/tsup.config.ts, pnpm-lock.yaml
- Use `tsup` for building client JS lib
- Allows to build CJS or ESM, + minify + splitting
=> fix: use tsup for building client js

.github/workflows/release.yml
- [ci] Fix pattern matching on tags (based on https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet)
- To be honest, not sure why, but `v0.0.1` wasn't matched
- With this one, it seems to work
- As, either way, the goal is not to be "super precise" (as regular expressions are not properly handled either way), but instead to be "precise enough so that the CI triggers only when we want it to be triggered"
- With that in mind, only matching on the semantic version and allowing any characters afterwards (`**`) should be enough
=> fix(ci): release tags pattern

clients/javascript/lib/gen_types/CalendarEventDTO.ts, clients/javascript/lib/gen_types/CreateEventRequestBody.ts, clients/javascript/lib/gen_types/UpdateEventRequestBody.ts, crates/api_structs/src/event/api.rs, crates/api_structs/src/event/dtos.rs
- Just adapted the comments on `CalendarEvent`'s `duration`, it should be `seconds` and not `minutes`
=> chore: fix duration comments (minutes => seconds)

clients/javascript/lib/gen_types/CalendarEventDTO.ts, clients/javascript/lib/gen_types/CreateEventRequestBody.ts, clients/javascript/lib/gen_types/UpdateEventRequestBody.ts, clients/javascript/tests/calendarEvent.spec.ts, crates/api/src/event/update_event.rs, crates/api_structs/src/event/api.rs, crates/api_structs/src/event/dtos.rs
- [CalendarEvent] `duration` is now in milliseconds
- [CalendarEvent] fix `end_time` not updated when `duration` and/or `start_time` are updated
- `end_time` cannot be provided when creating/updating a calendar event, but it should be updated when the other 2 are updated
- [CalendarEvent] When returning a CalendarEvent, also include `end_time` so that the consumer doesn't have to compute it
=> fix(calendarEvent): duration should be milli + add endTime + fix update

clients/javascript/lib/helpers/datesConverters.ts
- Fix `endTime` not being converted to Date in JS
=> fix: convert endTime to date

crates/infra/src/repos/status/postgres.rs
- This function is used by the healthcheck route, which is often called
- Filling APM storage with this route is not really useful, nor is it useful to know what is happening inside this route (as it does nothing)
=> chore: remove instrumentation on check connection

crates/api/src/shared/usecase.rs
- Changed usecases' logs from info to debug
- They can get quite noisy, and we already have the HTTP logger middleware
=> chore: convert some logs to debug

.github/workflows/_build-and-merge-docker.yml
- use self hosted runners to build.
=> [TS-3565]👷 ci: use self-hosted runners

clients/javascript/lib/gen_types/CreateEventRequestBody.ts, clients/javascript/tests/calendarEvent.spec.ts, clients/rust/src/event.rs, crates/api/src/event/create_event.rs, crates/api_structs/src/event/api.rs
- When creating a calendar event, allow to specify `created` and `updated`, which are timestamps for when the calendar event was created and updated
- Useful for us as, when double writing, we want to have the same dates on both sides (so that queries return the same)
=> feat(calendar events): allow to specify predefined created/updated (dates) when creating

clients/javascript/lib/gen_types/UpdateEventRequestBody.ts, clients/javascript/tests/calendarEvent.spec.ts, clients/rust/src/event.rs, crates/api/src/event/update_event.rs, crates/api_structs/src/event/api.rs
- Allow to specify the new `created` and `updated` when updating calendar events
=> feat(event): allow to override created and updated in "update"

crates/infra/.sqlx/query-7ca1e21500b0ee13496086f3258b98d9993127ede389814e6800822b0a7b7b57.json, crates/infra/.sqlx/query-dff6107515f942d02e2ca40164678d8ef1897aa84c8dc0a7a3ffca5a8747ef33.json, crates/infra/migrations/20250123000000_add_group_calendar_uid_index.sql, crates/infra/migrations/20250123000000_add_indexes_for_get_external_id.sql, crates/infra/src/repos/event/calendar_event/postgres.rs, debian.Dockerfile
- Refactored `get_by_external_id` (with groups) query and split it into 2 queries
- The use of `OR` is suboptimal
- Using `UNION ALL` could have worked, but it doesn't work well with sqlx (we lose the query check/type check)
- So I've split into 2 parallel queries, which shouldn't be too impacting performance-wise
- Fix: add an index on `calendar_uid` in `events_groups`
- Fix: add an index on `calendar_uid` in `calendar_events` (I was surprised that it's not there yet)
- Fix: add an index on `account_uid` in `users` (same, imo should have been there from the start)
=> fix(infra): improve performance of `get_by_external_id` (with groups)

clients/javascript/lib/baseClient.ts
- (js client) Add a timeout of 5s on both clients (frontend, backend)
- Avoids getting stuck indefinitely on a HTTP request
=> fix(js client): add default timeout of 5s

bins/nittei/src/main.rs, crates/api/src/status/mod.rs, crates/utils/src/config.rs
- Remove the whole "send 503" when shutting down, as after verification, it's an incorrect way to handle the shutdown
=> refactor(shutdown): avoid returning 503 and wait less

bins/nittei/Cargo.toml, bins/nittei/src/main.rs
- Changed default allocator from system allocator to jemalloc for all envs
- Default is nice, but from what I read, jemalloc is slightly better for long-running apps (e.g. it's the default for https://github.com/cloudflare/foundations)
=> feat: use jemalloc in all cases

crates/api/src/user/get_multiple_users_freebusy.rs, crates/api/src/user/get_user_freebusy.rs
- In freebusy / multiple freebusy, return a sorted array instead of the random order
=> fix(freebusy): sort by start_time

clients/javascript/lib/baseClient.ts, clients/javascript/lib/helpers/errors.ts, clients/javascript/tests/user.spec.ts, crates/api/src/user/create_user.rs
- Return a 409 conflict error when creating a user with an already assigned id/external_id
=> feat(user): return conflict error for external_id on create

clients/javascript/tests/calendarEvent.spec.ts, crates/api/src/event/create_event.rs, crates/api/src/event/update_event.rs, crates/domain/src/shared/recurrence.rs
- Fix an issue when checking RRULE (recurrence)
- `until` is expected to be a datetime with UTC timezone by the rrule library
- Added a few additional error logs in order to ease the debugging in the future
=> fix(recurrence): UNTIL should be UTC

clients/javascript/tests/calendarEvent.spec.ts, crates/api/src/event/create_event.rs, crates/domain/src/event.rs, crates/domain/src/shared/recurrence.rs
- Remove the check that limit the duration between `startTime` and `until` to be maximum 2 years
- I suppose it's to avoid having "too big" events
- But we have events with a bigger `until`, so we need to be able to handle it
=> fix(recurrence): allow big until values

crates/api/src/event/get_events_by_calendars.rs, crates/api_structs/src/event/api.rs
- Fix `getEventsByCalendars` - properly use only the calendars of the users, and none others
=> fix(getEventsByCalendars): use user_id

charts/nittei/templates/deployment.yaml, charts/nittei/values.yaml
- [helm] Allow to override `strategy` for the deployment (particularly useful for configuring `maxSurge`)
=> feat(helm): allow to specify deployment strategy

clients/javascript/lib/index.ts
- Expose the `axiosClient` in the JS types
- Right now, it's already assigned to the object, but not visible due to it being missing from the types
=> fix(js): expose HTTP client in type

clients/javascript/tests/requirements/loadTests.spec.ts
- Due to the additional DB indexes, creating new events is a little slower
- Reduced the nb of events created from 300 to 200 during the load test (as it sometimes times out)
=> test: reduce to 200 events  in load tests

clients/javascript/tests/account.spec.ts, crates/infra/src/repos/event/calendar_event/postgres.rs, crates/infra/src/repos/shared/query_structs.rs
- Fix wrong table being used when searching on `user_uid`
=> fix(search): wrong table used

Cargo.lock, clients/javascript/lib/gen_types/AccountSearchEventsRequestBody.ts, clients/javascript/lib/gen_types/AccountSearchEventsRequestBodyFilter.ts, clients/javascript/lib/gen_types/SearchEventsRequestBody.ts, clients/javascript/lib/gen_types/SearchEventsRequestBodyFilter.ts, clients/javascript/tests/account.spec.ts, crates/api/src/account/account_search_events.rs, crates/api/src/event/search_events.rs, crates/api_structs/Cargo.toml, crates/api_structs/src/account/api.rs, crates/api_structs/src/event/api.rs, crates/domain/src/shared/datetime_query.rs, crates/domain/src/shared/id_query.rs, crates/domain/src/shared/string_query.rs, crates/infra/src/repos/event/calendar_event/mod.rs, crates/infra/src/repos/event/calendar_event/postgres.rs
- Make "search events in account" safer
- Default limit to 200 events
- Do not allow unknown keys (e.g. typo)
- Do not allow empty body
- Add `externalId` as a field that can be queried
=> feat(search): add externalId, default limit + checks

clients/javascript/tests/calendarEvent.spec.ts, crates/api/src/event/create_event.rs, crates/api/src/event/update_event.rs, crates/api/src/service/get_service_bookingslots.rs, crates/api/src/user/get_multiple_users_freebusy.rs, crates/domain/src/event.rs
- [Breaking change] `end_time` now is always the provided `start_time + duration`, and doesn't depend on the recurrence
- I'm not sure why it was defaulting to changing `end_time` to MAX_UTC for recurring events tbh
- It makes more sense to have the default event fields contain the correct information about the "first instance", and leave the recurrence stuff (e.g. `until`) in the recurrence field/config
- I didn't have to change much in the tests (except removing the parameters), so looks like that behavior wasn't needed either way
=> fix(event): end time usages

crates/api/src/event/update_event.rs
- Force `start_time` and `duration` to be "updated" even if the values are the same
- Triggers update of `end_time`
- (Otherwise, events with a wrong `end_time` are not updated if the `start_time` and `duration` are the same)
=> fix: always use provided data

clients/javascript/lib/gen_types/RRuleOptions.ts, clients/javascript/tests/calendarEvent.spec.ts, crates/domain/src/shared/recurrence.rs
- Allow to override the week start for specific events (use calendar's settings by default)
=> feat: allow to override weekstart for specific events

clients/javascript/tests/helpers/fixtures.ts, clients/javascript/tests/requirements/loadTests.spec.ts
- Following the reduction of the default timeout of the client from 5s to 1s, the tests in the CI sometimes fail during the load tests on ARM
- This PR increases it back to 3s (only for load tests)
=> test(load tests): increase timeout of client

clients/javascript/tests/account.spec.ts, crates/infra/src/repos/event/calendar_event/postgres.rs
- Fix a typo when implementing search on `recurring_event_uid`
- Should have implemented a test 😅
=> fix: typo with recurring_event_uid

.github/workflows/js-client-test.yml
- Fix print step not executed when the CI fails
=> ci: always print logs

alpine.Dockerfile, alpineWithDD.Dockerfile, bins/nittei/Cargo.toml, bins/nittei/src/bin/migrate.rs, bins/nittei/src/lib.rs, bins/nittei/src/main.rs, charts/nittei/templates/deployment.yaml, charts/nittei/values.yaml, debian.Dockerfile, debianWithDD.Dockerfile
- SQL migrations can take some time, which makes the app unavailable to probes
- Application crashes and restarts, without finishing migration
- Crashloop
- Helm chart: allow to run SQL migrations via an initContainer
- Improve binary for running migrations
=> feat: run migrations in init container

clients/javascript/lib/helpers/datesConverters.ts, clients/javascript/tests/calendarEvent.spec.ts
- Convert `recurringUntil` to a Date in JS
=> fix: convert recurringUntil to date

crates/infra/migrations/20250319170000_add_new_indexes.sql
- Fix migration that should have `IF NOT EXISTS`, as the indexes need to be created in background in prod
=> fix: migration

Cargo.lock, crates/api/Cargo.toml, crates/api/src/job_schedulers.rs
- Fix one remaining `actix_rt` usage, switch it to `tokio`
- Use `reqwest` instead of `awc` as the HTTP client, as reqwest is multi-thread safe (awc isn't)
=> fix: wrong runtime used

Cargo.lock, crates/api/Cargo.toml
- Configure `reqwest` to use the Rust native TLS implementation, instead of openssl
- Fix https://github.com/meetsmore/nittei/actions/runs/14025924955/job/39264465443
- Easier to use (no need to install a dependency in Docker containers)
- https://www.memorysafety.org/
=> fix: use Rust tls

clients/javascript/lib/gen_types/CalendarEventDTO.ts, clients/javascript/tests/calendarEvent.spec.ts, crates/api_structs/src/event/dtos.rs, crates/domain/src/event.rs
- Add `duration` to the `recurring_until` field when computed, as otherwise doing `timespan.start < recurring_until` can miss some events if `recurring_until  === timespan.start`
=> fix: add duration to recurring_until

charts/nittei/templates/deployment.yaml, charts/nittei/values.yaml
- [helm] Add `deploymentLabels` value to allow specifying labels on the deployment itself
=> feat(helm): add deployment labels

Cargo.toml
- Use `lto = "thin"` as an option when building for release
- It can slightly improve the performance, at the cost of slightly longer compile time
- https://doc.rust-lang.org/cargo/reference/profiles.html#lto
- Used by tikv: https://github.com/tikv/tikv/blob/master/Cargo.toml#L435
- Used by linkerd: https://github.com/linkerd/linkerd2/blob/main/Cargo.toml#L15
=> feat: use thin lto when building for release

clients/javascript/tests/calendarEvent.spec.ts, crates/utils/src/config.rs
- Increased default duration limit from 200 days to 300 days
- Needed for us
=> fix: increase default query duration

crates/api/src/http_logger.rs
- Try to fix resource name used by Datadog for grouping calls together
- Right now, DD manages to group paths that have UUIDs, but not the ones with ObjectIds
- This PR uses the `matched_path` which contains the generic version `/{id}` instead of `/some-id`
=> fix(tracing): otel.name

Cargo.toml, debian.Dockerfile, debianWithDD.Dockerfile
- Configure `codegen-units` which allows more optimizations to be made at the cost of compile time (let's see how much)
- Change Debian Docker images from `slim` to distroless, as we only need `glibc`
=> refactor(debian): change to distroless and add more optimizations

charts/nittei/templates/deployment.yaml
- [helm] Remove `sh` usage in `migrationInitContainer`
=> fix(helm): remove sh

bins/nittei/src/telemetry.rs
- Fix sampler not configured for Otel tracing (it's correctly set for Datadog tracing)
=> fix(telemetry): set sampler for otel too

clients/javascript/tests/requirements/loadTests.spec.ts
- Skip testing load test in CI as it's flaky
- We can always run it manually when needed
- We are monitoring performance via our internal APM
=> test: skip flaky load test

crates/api/src/event/delete_event.rs, crates/api/src/event/get_event.rs, crates/api/src/event/get_event_instances.rs, crates/api/src/event/get_upcoming_reminders.rs, crates/api/src/event/mod.rs, crates/api/src/event/update_event.rs, crates/api/src/shared/auth/route_guards.rs
- Re-use the `calendar_event` fetched in the "hook" (now adapted to middleware) instead of re-querying the DB
- For some endpoints, we fetch the `calendar_event` in a hook in order to check beforehand that the account can access/update that event, however that event was then discarded, and then refetched inside the endpoint itself
- Instead, use the event we have already fetched
=> feat(event): avoid refetching - use route guard

Cargo.lock, bins/nittei/Cargo.toml, bins/nittei/src/main.rs, crates/utils/src/config.rs
- Allow to specify the number of workers for the Tokio multi_thread runtime
- Add a way to get additional runtime information (number of cores/workers/logical cpus assigned by OS and memory)
=> feat: allow to specify number of workers and print runtime info

charts/nittei/templates/deployment.yaml
- Fix `topologySpreadConstraints` position in the deployment config
=> fix: chart topology spread constraints

crates/infra/.sqlx/query-b01c514da6037175c6d6c4c0c2ffedd0b23035fabf4b8c4900c187880ad44e7e.json, crates/infra/src/repos/event/calendar_event/postgres.rs
- Fix the logic for fetching of exceptions of recurring events
- Now include both the ones that have `original_start_time` inside the timespan, and the ones that have `start_time` inside, but `original_start_time` outside (as they also impact the timespan)
=> fix: also include events now planned during timespan

crates/api/src/account/get_account.rs, crates/api/src/event/create_batch_events.rs, crates/api/src/event/get_event_instances.rs, crates/infra/src/repos/event/calendar_event/postgres.rs
- Adapted a few places so that the errors are created lazily instead of eagerly
- Avoids paying the cost of capturing (uselessly) the stack trace in happy paths
- Profile shows that under load, most of the CPU is spent in `try_from` function of `CalendarEvent`, and particularly for anyhow's errors, even though the number of errors is very low
=> fix: avoid capturing stack traces in hotpaths

bins/nittei/src/telemetry.rs, crates/api/src/http_logger.rs, crates/utils/src/config.rs
- [config] Simply a little how the configuration for observability is handled
- Keep the default values in the config.rs file, instead of having them in multiple places
=> fix(telemetry config): simplify default values

bins/nittei/src/telemetry.rs, crates/utils/src/config.rs
- For some use cases, it's useful to fully disable the tracing (e.g. when running scripts, to avoid increased costs)
- Added a env var to fully disable tracing
=> feat: add flag for fully disabling tracing

crates/api/src/account/account_search_events.rs, crates/api/src/event/search_events.rs, crates/api/src/shared/usecase.rs
- Re-add tracing/instrumentation on the main `execute` functions, but set the level to `DEBUG`
- Instead of using undocumented `1000` value for the default limit on searches, use the configured `max`
=> feat: re-add spans on `execute`, but as `debug` + use max config for searches

clients/javascript/lib/accountClient.ts, clients/javascript/lib/baseClient.ts, clients/javascript/lib/eventClient.ts, clients/javascript/tsconfig.json
- Increase scope of HTTP requests that can be retried - include POST endpoints that are used for searching events
=> fix(js client): increase scope of retries

clients/javascript/lib/accountClient.ts, clients/javascript/lib/calendarClient.ts, clients/javascript/lib/eventClient.ts, clients/javascript/lib/helpers/datesConverters.ts, clients/javascript/lib/userClient.ts
- Adapted code so that we avoid re-allocating arrays when converting datestrings to proper dates
=> refactor(js client): avoid allocating new arrays when converting to dates
